# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = pro2.o
LINKOBJ  = pro2.o
LIBS     = -L"C:/Dev-Cpp-5.11/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32
INCS     = -I"C:/Dev-Cpp-5.11/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Dev-Cpp-5.11/MinGW64/x86_64-w64-mingw32/include"
BIN      = pro2.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

pro2.o: pro2.cpp
	$(CPP) -c pro2.cpp -o pro2.o $(CXXFLAGS)
