# Project: jee
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = jee.o
LINKOBJ  = jee.o
LIBS     = -L"C:/Users/Max Angelo Perin/OneDrive/Local Disk C/Dev-Cpp-5.11/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32  -luser32 -m32
INCS     = -I"C:/Users/Max Angelo Perin/OneDrive/Local Disk C/Dev-Cpp-5.11/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Users/Max Angelo Perin/OneDrive/Local Disk C/Dev-Cpp-5.11/MinGW64/x86_64-w64-mingw32/include"
BIN      = jee.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

jee.o: jee.cpp
	$(CPP) -c jee.cpp -o jee.o $(CXXFLAGS)
